name: autoGrader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
    - name: Setup dependencies
      run: |
          sudo apt-get install -y g++-10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
    - name: install_valgrind
      run: sudo apt update && sudo apt install -y valgrind
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -S .
    - name: make
      run: make
    - name: ctest
      run: ctest --output-on-failure
    - name: memory tests
      if: success() || failure()
      run: make valgrind
